name: tech_task
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  awesome_dio_interceptor: ^1.0.0
  chips_choice: ^3.0.0
  cupertino_icons: ^0.1.2
  dio: ^5.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_lints: ^2.0.1
  flutter_riverpod: ^2.3.4
  hooks_riverpod: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
